name: Trigger CLI Update

on:
  repository_dispatch:
    types: [ocm-cli-release]

jobs:
  triggerUpdate:
    runs-on: ubuntu-latest
    steps:
    - name: Replace version string
      run: |
        TAG=${{ github.event.client_payload.tag }}
        sed -i "s/latest_version = .*/latest_version = \"$TAG\"/" ./params.toml
