name: Trigger CLI Update

on:
  workflow_dispatch:
  repository_dispatch:
    types: [ocm-cli-release]

jobs:
  triggerUpdate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Do nothing
      if: github.event.client_payload == ''
      run: |
        echo "No dice"
    - name: Replace version string
      if: github.event.client_payload != ''
      run: |
        echo github.event.client_payload
        TAG=${{ github.event.client_payload.tag }}
        sed -i "s/latest_version = .*/latest_version = \"$TAG\"/" ./params.toml
        cat ./params.toml
